### ISSUE TITLE
Top menu is hidden

### ISSUE THREAD

**Issue by Mx74** [aspangaro/oblyon#108]
Ubuntu 21.10, on all browser installed (Firefox, Brave, Chrome, Beaker), the top menu scroll down is hidden by the mai ncaption when entering an item (Order, Invoice, Product, etc...)

Pics tell it better: 

![Capture d’écran de 2022-04-29 11-32-30](https://user-images.githubusercontent.com/23337492/165920556-fbfb873b-cd8c-48ad-a707-fa15dd0aa680.png)
![Capture d’écran de 2022-04-29 11-32-42](https://user-images.githubusercontent.com/23337492/165920563-619dcdd3-ad72-410f-8bde-1cc3c25a8ef4.png)

**Comment by aspangaro** [comment]
Old issue fixed with FIX_AREAREF_TABACTION enabled
