### ISSUE TITLE
Dolibarr 7.x

### ISSUE THREAD

**Issue by seldimi** [aspangaro/oblyon#13]
I just wanted to pop in and say how greatful I feel that this is open source than paid solution for dolibarr. Its among the best themes to download and use. 
A question, do you plan to upgradte to dolibarr 7.x at the moment?

**Comment by madmath03** [comment]
I tested this theme today with Dolibarr 7.0 and didn't found anything looking weird or different from Dolibarr 6.0.

@seldimi Did you encounter any issues with this theme on 7.0 ? I might be interested to take a look at them if you find any.

@aspangaro What would you prefer : 
- to wait until the theme is considered stable for 6.0 then create a new branch in beta for 7.0
- create the 7.0 beta branch from the 6.0 now and maintain both at the same time
?

**Comment by withheld** [comment]
madmath03, how do list pages look? Also, thank you for your effort, the base theme is nice and great to see someone cleaned it up. Going to test it out over the weekend.

**Comment by madmath03** [comment]
@withheld As you can see next, I didn't seem to find anything different between 6 and 7, but I am still discovering Dolibarr so there might be more things to test.
![oblyon_dolibar_6 0](https://user-images.githubusercontent.com/6967675/36898436-2528fe0e-1e1b-11e8-83c8-35d19888a790.png)
![oblyon_dolibar_7 0](https://user-images.githubusercontent.com/6967675/36898443-288a9abc-1e1b-11e8-971c-591fb4fb5eca.png)

I also think the theme looks great and it was a shame that it was not stable yet. Good thing it was OpenSource :)

**Comment by madmath03** [comment]
Well, I did find some differences.
2 so far:
- the odd/even management in the user permissions view is handled differently and ends up looking a bit weird.
- when enabling the bank module, the top menu link points to `compta/bank/index.php` which has been renamed to `list.php`, so you get a 404...

**Comment by madmath03** [comment]
I created a 7.0 branch on my fork that should solve most of the compatibility issues with Dolibarr 7.0.

@aspangaro If you can create the branch 7.0, I can then send you the PR.
