### ISSUE TITLE
Category Pup-Up don't show existing categories in DB v18

### ISSUE THREAD

**Issue by choybe** [aspangaro/oblyon#133]
Hi, since update to Dolibarr v18 the category pop-up choice list when editing is not working not visible anymore, no matter which category. It is e.g. possible to choose a supplier froim the list within the category menu but not a category within the third-party.
When clicking into the category field there is a fine line pop-up to see, but no category visible or choosable within the-pop-up. See about attached file. - When disabling Oblyon module,. the category pop-up works again. The error must be at Oblyon. But where?
Example shown is on Dolibvarr 18.01 and Oblyon 2.2.8

![Category-Pop-Up-Error-Oblyon](https://github.com/aspangaro/oblyon/assets/12556122/68097423-5674-4681-96f4-1fbc4f95e217)

**Comment by aspangaro** [comment]
Thanks for your report. Fix are present in new version 2.2.10 available in branch v14 or 2022.5.3
