### ISSUE TITLE
Extract menu from Theme

### ISSUE THREAD

**Issue by kevinseebach** [aspangaro/oblyon#39]
Hi and thanks for the theme.

EN
Is it possible to extra the menu from the theme to use it with another theme like Eldy ?
Which files are used to render the menu ?

FR 
Est ce possible d'extraire le menu du thème pour l'utiliser avec un autre theme (eldy par exemple) ?
Quels fichiers sont utiliser pour le rendu du menu ? (les 2 fichiers dans le dossier menu ?, variable propre au module ?)

Merci

**Comment by aspangaro** [comment]
Bonjour,

Le menu du thème Obyon est exportable avec beaucoup de travail car il n'utilise pas le même rendu et il a de nombreuses variables lui appartenant sans compter les css.

Bon courage
