### ISSUE TITLE
Top menu is overlapped by company logo

### ISSUE THREAD

**Issue by seldimi** [aspangaro/oblyon#46]
Hello.
If you have top bar, it overlaps as div.vmenu has z-index: 20 but top bar ULs have none
Dolibarr 8

**Comment by madmath03** [comment]
Hello,
I'm not sure to follow you there or I'm not able to reproduce...
Could you provide a small gif or screenshot of the issue you are encountering and a copy of the plugin's menu configuration ?

**Comment by seldimi** [comment]
![image](https://user-images.githubusercontent.com/4827399/47746032-ce091000-dc8d-11e8-8c4f-41b483ce9ceb.png)
