### ISSUE TITLE
Version 9.0.1 Branch 9.0

### ISSUE THREAD

**Issue by saiff54** [aspangaro/oblyon#59]
the customization panel in the modules doesn't load Blank page, and the logo on the second menu doesn't load it says this error
DolibarrHasDetectedError.

RequestedUrl: /viewimage.php?cache=1&modulepart=companylogo&file=favicon-3.png
Referer: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
MenuManager: 
Message: Error call dol_check_secure_access_document with not supported value for modulepart parameter (companylogo)

**Comment by Leboubou111** [comment]
Same error
And when I apply oblyon theme, I have a page without CSS style.

Do you have an idea ?

Dolibarr 9.0.1

**Comment by madmath03** [comment]
@saiff54 The customization panel seems to have a syntax error, thus causing the page to crash and generate the blank page. I will try to fix it this WE. Regarding the "_logo on the second menu _", I'm not sure to follow you... could you share a logo of what you are referring to ?

@Leboubou111 You mentioned that you applied Oblyon theme, but did you enable the Oblyon module as well ? It is needed for the theme to properly work, so I wouldn't be surprised if the absence of CSS Style is due to that.

EDIT: I just pushed the fix for the admin menu and added some documentation on install / usage. 
Can you guys check if that solves your issue ?

**Comment by Leboubou111** [comment]
Yep, it's OK for me with your fix update.
Juste the Logo "mycompagny" doesn't appears on left when logged. (png file)
No problem on logon page.

![image](https://user-images.githubusercontent.com/8314926/55672443-7c4b5e00-589b-11e9-8c2e-acbdf2061a6b.png)


And, can you please give me the code modification (line to CSS file) to start the top menu after logo ? (same to "md" theme)

Many Thanks

**Comment by madmath03** [comment]
Okay, I think I got it. Just pushed it now.

Regarding your other question... there will probably be a lot more than one line to impact as the theme is not expected to do that.
You will have to look in `styles.css.php` the rules affecting `#id-left`, `#id-right`, etc...

But there are a lot of options in the admin menu. Maybe you can find some configuration that would match more closely what you desire.

**Comment by Leboubou111** [comment]
Like... 👍 

But when I change style.css.php file, no modification apply.
I would like change this
`.sec-nav__sub-list { 
	background-color: <?php print $bgnav; ?>;`

to : 
`.sec-nav__sub-list { 
	background-color: (85, 85, 85);`

**Comment by madmath03** [comment]
Well, it certainly will not work since `background-color: (85, 85, 85)` is not valid CSS...

But again, take a look at the Oblyon module admin configuration, and in this case the Colors tab. You can set the colors of this theme there.

**Comment by Leboubou111** [comment]
Juste changed by `rgb(xx, xx, xx)` and it's OK.
Yep, I like possibility configuration in your module but not possible for left submenu. 👍 
Juste to see a different (cut) --> background left menu and background left submenu.

Now I search to adjust marge main menu (top menu), I will find, I wil find ;-)

Do you think Oblyon theme it's compatible with drop down menu module ?
https://www.dolistore.com/fr/modules/1061-Menu-D--roulant.html

Many thanks for your devepement, it's a verry good theme and possibility to personalise. Realy good job.

**Comment by madmath03** [comment]
Glad you enjoy this 😃 

Hard to say if drop down menu will be compatible... The source is not available and the demo does not provide admin rights or even rights to change current theme.
I suppose this module replaces the theme's menu handler by its own to generate the sub lists to be displayed when mouse hovers the main menu, so I'm afraid it might only be compatible with Eldy but I might be wrong.

I would be curious to know the result so do not hesitate to share if you think there is any technical issues in this theme that prevent compatibility with custom menu mangers.

Unless you find some side effects on the fixes done here, I will close this issue and reopen if needed.

Good luck 😉
