### ISSUE TITLE
CSS problem on v10.0.1

### ISSUE THREAD

**Issue by maverjk** [aspangaro/oblyon#61]
I know that the last version is not completely suitable for Dolibarr 10.0.1, however I tried to give it a go and for what I can actually see there should be only a missing CSS reference in "topmenu-login-dropdown". With click button is automatically added "open" reference, but I'm afraid that this has been removed or not found in loaded CSS stylesheets. 
I presume that this should be an easy fix, where I can find the correct "open" reference?

**Comment by antho2305** [comment]
Looks like all features are applied and works well only button which remains with eldy theme don't know why

**Comment by maverjk** [comment]
For what I saw there was a problem with notification pop-up. I just tested the one that appears hovering on username in top bar and here as already described there is a miss reference to "open" class. It is possible that has been removed or not properly loaded the correct CSS

**Comment by aspangaro** [comment]
@maverjk I work on this theme next week. Can you add some pictures of your problem to simplify, please ? Thanks in advance

**Comment by Leboubou111** [comment]
@aspangaro I've some (minor) problem with your theme.
Would you like a new ticket ? You prefer in English or French words ?

**Comment by maverjk** [comment]
This is what looks like on Dolibarr 10.0.1
![Screenshot (9)](https://user-images.githubusercontent.com/3779181/63428854-d4cd6300-c418-11e9-8b77-17fa0d45a571.png)

**Comment by aspangaro** [comment]
Have you try F5+CTRL on your browser ?

Alexandre Spangaro

________________________________

**Comment by aspangaro** [comment]
@all please one issue by problem. In english or french and please add screenshot of your problem. Thanks

**Comment by aspangaro** [comment]
Please move to Oblyon v11. Have a nice day
