### ISSUE TITLE
2nd sub-menu alignment

### ISSUE THREAD

**Issue by Leboubou111** [aspangaro/oblyon#62]
Les sous menus des sous-menus ne sont pas bien alignés.

![doli_sub_menu_oblyon](https://user-images.githubusercontent.com/8314926/63447315-17ecfd80-c43c-11e9-8706-0d86b1ad906b.png)

Manque ce code en CSS :
.menu_contenu.sec-nav__sub-item.item-level3 {
     padding: 0.2em 2em;
}

Puisse que .menu_contenu.sec-nav__sub-item.item-level2 a un padding: 0.2em 1em
Afin d'avoir une tabulation supplémentaire par rapport à son parent.

Du coup avec la largeur de nos écrans actuels il faudrait agrandir le left-menu :
.vmenu {
     min-width: 250px;
}

Par contre je n'ai pas trouvé comment agrandir les champs "search" et "bookmark".

**Comment by aspangaro** [comment]
C'est corrigé dans la v10 du thème, je viens de mettre à jour la v9 pour répercuter le changement. Pas besoin d'agrandir le menu.

![image](https://user-images.githubusercontent.com/2341395/63487382-3d652000-c4ab-11e9-84e7-7aaaa44fd0f7.png)

https://github.com/aspangaro/oblyon/commit/2810de54aac2787163833950284555a6fb993a3f

**Comment by Leboubou111** [comment]
Merci Alexandre.
