### ISSUE TITLE
Fixed Menus

### ISSUE THREAD

**Issue by Leboubou111** [aspangaro/oblyon#63]
Est-il possible de fixer les menus (haut et gauche). Ou d'en faire une option ?

@media (min-width: 981px) {
     #id-top {
          position: fixed;
          top: 0;
          left: 0;
          width: 100%;
     }

     .vmenu {
          position: fixed;
          left: 0;
          top: 54px;
     }

     .id-container {
          margin-left: 260px !important;
          margin-top: 54px !important;
     }
}

ou même plutot :

@media (min-width: 981px) {
     #id-top {
          position: fixed;
          top: 0;
          left: 260px;
     }

     .vmenu {
          position: fixed;
          left: 0;
          top: 0px;
     }

     .id-container {
          margin-left: 260px !important;
          margin-top: 54px !important;
     }
}

**Comment by Leboubou111** [comment]
Si le menu de gauche n'est pas agrandit il faut dans ce cas remplacer 260px par la valeur actuelle soit 220px (à mes souvenirs)...
Mais bon je pense que tu maîtrises le sujet 😉

**Comment by Leboubou111** [comment]
J'ai vu la modif sur la v11 pour fixer les menus.
Celui du haut fonctionne, par contre, le menu left ne fonctionne pas.

**Comment by aspangaro** [comment]
Non toujours pas, il faut que je trouve un moyen. Je laisse l'issue ouverte, je me mettrai dessus sous peu.

**Comment by Leboubou111** [comment]
Bonjour Alexendre (@aspangaro )

Je mets la possibilité de fixer le menu dans l'autre post : https://github.com/aspangaro/oblyon/issues/66
