### ISSUE TITLE
V11.0.0 Login page is broken

### ISSUE THREAD

**Issue by endclose** [aspangaro/oblyon#65]
Hi everyone,

I was trying the V11 it has a problem in the Login Page. As you can se in the following image it's broken

![oblyon11-login-page](https://user-images.githubusercontent.com/60682097/73810391-fc806f80-479b-11ea-9ab5-3d16d1d3459b.png)

**Comment by Leboubou111** [comment]
Same problem on Oblyon v11 and Dolibarr v11

**Comment by aspangaro** [comment]
Bonjour, c'est réparé dans la mise à jour de ce matin.

Pour la version payante d'Oblyon sur Easya, on utilise une autre page de login... Voilà ce que ça donne en temps normal :
https://demo.open-dsi.fr/dlb/
