### ISSUE TITLE
Quelque problème

### ISSUE THREAD

**Issue by Leboubou111** [aspangaro/oblyon#67]
3 petits problèmes relevés :

1. Le nom du sous menu dans les propositions commerciales : 

![image](https://user-images.githubusercontent.com/8314926/74472912-05132d00-4ea3-11ea-8239-f45abd72f243.png)

2. Sur mobile : les tabs affichées en modal ont un problème avec le z-index... Il faudrait mettre un z-index à 2 : 

![image](https://user-images.githubusercontent.com/8314926/74473050-3be94300-4ea3-11ea-9636-69dbc93a82b4.png)

3. Sur mobile : à la création/modification d'un tiers, le form deborde : 

![image](https://user-images.githubusercontent.com/8314926/74473106-53c0c700-4ea3-11ea-8851-54de6eba881b.png)

**Comment by aspangaro** [comment]
Bonjour,

Quelques problèmes en cours de correction.

1. C'est un problème portant sur un module externe, il suffit de rajouter la clé de traduction pour que tout se remette d'aplomb, c'est la clé de langue qui est trop longue sans espace.

2. Pour le problème de z-index, c'est commun à Dolibarr, soit il faut retirer la constante MAIN_MAXTABS_IN_CARD en attendant soit attendre que le patch suivant soit intégré dans Dolibarr : 
https://github.com/Dolibarr/dolibarr/pull/13150  

3. Corrigé dans la prochaine mise à jour.
