### ISSUE TITLE
Change request on style.css.php

### ISSUE THREAD

**Issue by keide** [aspangaro/oblyon#72]
Hello, I'm sorry but I don't use Git...

There is a problem with last version of Oblyon. It doen't take into account the value of THEME_ELDY_USE_CHECKED if THEME_ELDY_ENABLE_PERSONALIZED is on.

This is the change to do:

> "style.css.php", line 289, add this:
> `$colorbacklinepairchecked = empty($user->conf->THEME_ELDY_ENABLE_PERSONALIZED)?(empty($conf->global->THEME_ELDY_USE_CHECKED)    ?$colortext:$conf->global->THEME_ELDY_USE_CHECKED)             :(empty($user->conf->THEME_ELDY_USE_CHECKED)?$colorbacklinepairchecked:$user->conf->THEME_ELDY_USE_CHECKED);`
> 
> between line:
>  `$colortextlink       =empty(.......`
> and line:
>  `$fontsize            =empty(.......`

Thanks in advance!

Best regards,
JJ

**Comment by aspangaro** [comment]
Old issue
