### ISSUE TITLE
Proposition commercial fournisseurs

### ISSUE THREAD

**Issue by JackPetard** [aspangaro/oblyon#73]
Bonjour,

Dans le menu commerce, les propositions commerciales fournisseurs n'apparaissent pas.
![Sans titre](https://user-images.githubusercontent.com/77309032/104257764-71fdc100-547e-11eb-97dd-b8694c22ebec.png)

Si je desactive le module Oblyon, cela revient
![Sans titre2](https://user-images.githubusercontent.com/77309032/104257964-e6d0fb00-547e-11eb-822d-30f0b0dbcdd3.png)

**Comment by Leboubou111** [comment]
En effet, j'avais jamais fait attention n'utilisant que très très rarement ce module.
J'ai regardé dans le code HTML, le "li" n'apparait pas dans le "ul"
@aspangaro : une idée ?

**Comment by JackPetard** [comment]
Bonjour,

J'ai forcé l'affichage en écrivant un bout de code dans oblyon.lib

voila le message : non autorisé et tout est grisé, le module est bien activé, ca peut peut etre aidé à la découverte

![Screenshot_1](https://user-images.githubusercontent.com/77309032/104509400-e739d500-55e9-11eb-861e-0fbdda272f2e.png)

**Comment by aspangaro** [comment]
Bonjour,

Le menu automatique a été retiré du module (par mes soins en plus...) pour se trouver désormais dans les menus, il faut que je rajoute le nécessaire à partir de la v12. Merci du retour.

**Comment by aspangaro** [comment]
C'est réparé
