### ISSUE TITLE
Bouton selectedfields ne fonctionne pas

### ISSUE THREAD

**Issue by JackPetard** [aspangaro/oblyon#74]
Bonjour,

Dans les listes, le bouton permettant de sélectionner les titres n'affichent rien en cliquant dessus.
![Sans titre](https://user-images.githubusercontent.com/77309032/104309750-f1b57b00-54d2-11eb-8408-e36391537f7b.png)

Alors qu'il devrait afficher ceci 
![Sans titre2](https://user-images.githubusercontent.com/77309032/104309866-1e699280-54d3-11eb-9c68-a1f1feafd60d.png)

**Comment by Leboubou111** [comment]
Ca s'affiche bien de mon coté...
Tu es en quelle version Dolibarr ?

![image](https://user-images.githubusercontent.com/8314926/104310131-7e603900-54d3-11eb-8b20-b50c679f2d76.png)

**Comment by JackPetard** [comment]
Version 12.0.4

**Comment by Leboubou111** [comment]
Je suis en 11.0.4, avec Oblyon 11.0.0

**Comment by JackPetard** [comment]
D'accord,

quand je clique cela m'ajoute #selectedfields dans l'URL (comme list.php?leftmenu=orders#selectedfields) mais la petite fenetre ne s'ouvre pas, je vais chercher

**Comment by Leboubou111** [comment]
Oui.
Mais il y a du JavaScript qui tourne au clique de cet élément.
Il sélectionne le UL avec la classe "ulselectedfields" du $('dl.dropdown') pour lui faire un .toggle() ou .show()

**Comment by Leboubou111** [comment]
Quel était le problème ?

**Comment by JackPetard** [comment]
Bonsoir

C’est revenu en désinstallant et en réinstallant le thème .

Il reste le menu des demandes de prix fournisseurs qui ne s’affichent pas .
