### ISSUE TITLE
problème à l'activation sur une instance 13.0.0

### ISSUE THREAD

**Issue by macrofsky** [aspangaro/oblyon#75]
Bonjour, 
je rencontre une erreur lors de l'installation d'oblyon sur une instance 13.0.0.
Par contre, je ne peux pas reproduire l'erreur sur mon wamp...
si vous avez une idée de mon soucis je suis preneur !
 
NB : les erreurs annoncent dolibarr-10.0.2 mais c'est bien la V13, j'ai conservé le chemin en 10.0.2 pour ne pas avoir à toucher à la CRON chez mon client

Warning: count(): Parameter must be an array or an object that implements Countable in /homepages/17/d438809266/htdocs/ADMIN/dolibarr-10.0.2/htdocs/core/lib/admin.lib.php on line 1086

Warning: Cannot modify header information - headers already sent by (output started at /homepages/17/d438809266/htdocs/ADMIN/dolibarr-10.0.2/htdocs/core/lib/admin.lib.php:1086) in /homepages/17/d438809266/htdocs/ADMIN/dolibarr-10.0.2/htdocs/admin/modules.php on line 277

**Comment by aspangaro** [comment]
Je n'arrive pas à reproduire cette erreur. Cela concerne plutôt la v13 à mon humble avis.

**Comment by macrofsky** [comment]
oui c'est bien une v13, comme indiqué dans l'objet de mon issues
