### ISSUE TITLE
liens menus salaires

### ISSUE THREAD

**Issue by macrofsky** [aspangaro/oblyon#78]
bonjour,
je rapporte les bugs rencontrés sans en attendre de correction je précise, je me fais mes corrections de mon côté.
lorsque j'active le module oblyon (sur V 13.0.1), les liens vers le menu salaires (facturation/dépenses spéciales/salaires) sont erronés (domaine.fr/compta/salaries/list.php?leftmenu=tax_salary&mainmenu=billing)
de mon côté je dois virer le compta de l'url cible
(domaine.fr/salaries/list.php?leftmenu=tax_salary&mainmenu=billing)

si le module oblyon n'est pas actif je n'ai pas le soucis.
merci tout de même pour cet excellent thème.

**Comment by aspangaro** [comment]
Bonjour,

Télécharger la dernière version de la branche 13, c'est un problème corrigé depuis le 18 février 2021.
https://github.com/aspangaro/oblyon/commit/644d5e69bfb4121285670a2964e1eb3a23f3ba29

Excellente journée
