### ISSUE TITLE
Menüpunkt "Kategorien" fehlt unter Produkten und Leistungen

### ISSUE THREAD

**Issue by stefanwz** [aspangaro/oblyon#79]
Hallo,

ich habe das obylon-template auf meinem Dolibarr 13.0.3 mit deutscher Spracheinstellung installiert.
Wenn ich das Template aktiviere funktioniert auch alles so wie es soll... bis auf 2 Punkte:

1. Im Top-Menü steht statt dem Punkt "Produkte | Leistungen" dann "catalog"
Das ist der einzige Menüpunkt, bei allen anderen steht die korrekte deutsche Bezeichnung.

2. Wenn ich in den Punkt "catalog" (Produkte) gehe, dann fehlen in den Unterpunkten bei "Produkte" und bei "Leistungen" jeweils der Punkt "Kategorien".
Der einzelne Menüpunkt "Kategorien" darunter mit "Kategorien anlegen" ist aber vorhanden.

Meine Fragen sind logischerweise: Warum? und wie kann ich das lösen?

**Comment by aspangaro** [comment]
Hallo,

Können Sie zum besseren Verständnis ein Bild zur Verfügung stellen?

Vielen Dank im Voraus,

**Comment by stefanwz** [comment]
Hallo,

danke für die schnelle Rückmeldung.
Ja, mit Bilder ist das wohl einfacher erklärt.

zu 1.: 
Ich habe herausgefunden, das "Kategorien" jetzt nur ein extra Punkt ist, statt wie davor in "Produkte" und "Leistungen" integriert.
Der Punkt hat sich damit erledigt.

zu 2.:
Können Sie mir sagen für welche beiden Variablen ich eine Übersetzung anlegen muss ("Produkte" & "Buchhaltung")?


Eldy-Template:
![Screenshot eldy-template](https://user-images.githubusercontent.com/86561364/123670763-d8fd0f80-d83d-11eb-8f3d-1d64594f4692.jpg)

Oblyon-Template:
![Screenshot oblyon-template](https://user-images.githubusercontent.com/86561364/123670759-d8647900-d83d-11eb-8447-ea0ff6987575.jpg)

**Comment by aspangaro** [comment]
Old issue. Use personnalized traduction for menu catalog in deutsch
