### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by Ilgegenio** [aspangaro/oblyon#80]
Bonjour,

Il y a t-il une possibilité d'afficher seulement les icônes sur le menu haut quand on passe sur un affichage téléphone.

Sur le menu haut, toujours en affichages téléphone lorsque l'on clique sur un onglets ça déroule le menu mais l'index du menu semble être un lien cliquable ce qui ne laisse pas le temps de cliquer sur les sous menus

**Comment by aspangaro** [comment]
Old issue - Seem fix now
