### ISSUE TITLE
inquiry about oblyon updates

### ISSUE THREAD

**Issue by javieralapps4up** [aspangaro/oblyon#81]
Hello Aspangaro, Are you going to continue updating Oblyon?

I could help you if you give me some instructions

Thanks in advance, this theme is fantastic

**Comment by javieralapps4up** [comment]
I can translate to Spanish completely

I can update the menus if you help me identify the source

I have a lot of free hours and a lot of interest in continuing to use this theme in future versions of Dolibarr

Please just tell me how can I help you

**Comment by aspangaro** [comment]
Hi @javieralapps4up 

Sorry, I don't view your message. I publish a first version compatible with v14 of Dolibarr & Easya Solutions (This is the main template of this particular version of Dolibarr).

See branch v14
