### ISSUE TITLE
Icons missing

### ISSUE THREAD

**Issue by mverove** [aspangaro/oblyon#82]
Hello,

* Dolibarr version: 14.0.4
* Oblyon version: 14.0.4

There are icons missing in the secondary menu:
![image](https://user-images.githubusercontent.com/96298151/148034510-2fbb944b-ee78-4ad3-91fc-ee975d8db4d4.png)
![image](https://user-images.githubusercontent.com/96298151/148034527-87bcf2c3-cac1-467b-bdb7-a5171ea9d651.png)
![image](https://user-images.githubusercontent.com/96298151/148034533-e54d0145-dcfd-40c8-aa71-bfb90ad6b08b.png)

Thank you in advance !

**Comment by aspangaro** [comment]
Hi @mverove 

Fix on branch v14 for Dolibarr & 2022.4 for Easya.

Please download last version
