### ISSUE TITLE
Text alignement in sub-menu

### ISSUE THREAD

**Issue by mverove** [aspangaro/oblyon#83]
Hello,

* Dolibarr version: 14.0.4
* Oblyon version: 14.0.4

The Users & Groups sub-menu looks not correctly aligned (no indent):
 ![image](https://user-images.githubusercontent.com/96298151/148034839-6204fd6e-5831-43bd-93e8-70fb8871841c.png)

Thank you in advance.

**Comment by aspangaro** [comment]
Hi @mverove

Fix on branch v14 for Dolibarr & 2022.4 for Easya.

Please download last version
