### ISSUE TITLE
Search contact missing

### ISSUE THREAD

**Issue by dolibarr95** [aspangaro/oblyon#84]
Hello

I use the theme with Dolibarr 14
In the quick search menu "contact" option is no longer available.
![Capture](https://user-images.githubusercontent.com/24292300/148185174-b7c2bb20-ae50-49f4-9a61-9b2e25063cee.PNG)

Tks

**Comment by aspangaro** [comment]
Solved with https://github.com/aspangaro/oblyon/commit/b86fe1c9598d0d3a940c1eefa14acfe62c584e15

**Comment by dolibarr95** [comment]
Tk you so much !!
