### ISSUE TITLE
The central panel gets shifted to the right, instead of filling the whole screen.

### ISSUE THREAD

**Issue by jacmart** [aspangaro/oblyon#97]
Hi,

there seem to be a new bug within the v13 - in a situation when menus (top<-->side) are inverted and the folding / unfolding function is activated to gain some more screen width.

The central pannel is now generally shifted to the right side, whatever the left menu condition is (folded or unfolded), whereas in previous versions (v11) the pannel would always use the whole width of the screen. The left menu would than partly cover the central panel when unfolded.

![oblyon ferme](https://user-images.githubusercontent.com/11412063/156060269-6d71455c-9ec5-46db-b7bb-d6d2a4a240eb.jpg)
![oblyon](https://user-images.githubusercontent.com/11412063/156060275-e17d7438-0055-48a2-ae86-ad380701709d.jpg)

Can the old behavior be restored?

**Comment by aspangaro** [comment]
Old issue - Seem fix now
