### ISSUE TITLE
Hide Left Menu, option setting disappears

### ISSUE THREAD

**Issue by binerf** [aspangaro/oblyon#98]
Hello,

In the module configuration, once you activate _Hide Left Menu_ option, on/off button related to this option disappears and it gets impossible to disable hiding of left menu.

Activation:
![image](https://user-images.githubusercontent.com/10645373/156402048-9d87b09a-1bd7-41be-a05e-ac9aba01e778.png)

on/off button disappears:
![image](https://user-images.githubusercontent.com/10645373/156402124-974d94a7-a583-4e3f-9f95-d16e0d2c0ce3.png)

Thank you

**Comment by aspangaro** [comment]
Hi @binerf ,

I can't reproduce, what is your version of Dolibarr ? And it's a migration or not and if yes from which version of Dolibarr ?

Thanks in advance

**Comment by binerf** [comment]
Hi @aspangaro ,

It's not a fresh install.
Dolibarr 14.0.5, multiple upgrades from 10.0.7.

![image](https://user-images.githubusercontent.com/10645373/156931887-f5e21c49-4661-4593-8c05-be646ddac24e.png)

Thanks

**Comment by aspangaro** [comment]
Hello,

Thanks for your return, this problem coming from a future fonction to colorize button.

You can download new version on branch 14.0

https://github.com/aspangaro/oblyon/commit/bd0421e7d21efe5fc5b6d4c85b71eeeeb8062449

Have a good day !

**Comment by binerf** [comment]
Hi @aspangaro ,

It's been fixed !!

Thank you !
